# Generated by Django 4.1.4 on 2023-03-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_goods_quantity_basketitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Product',
        ),
    ]
