# Generated by Django 4.1.4 on 2023-03-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_basketitem_quantity_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.product')),
            ],
        ),
    ]
