# Generated by Django 4.1.4 on 2023-04-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='users/default_user_img.png', upload_to='users/'),
        ),
    ]
